/**
 * Reference for most of the types used in the Windows API. Some of the types have been altered to better fit
 * the C-types I have access to in Koffi. For example, `__int64` has been replaced with `int64_t`.
 *
 * @see https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types
 */

#include <windows.h>
#include <cstdint>
#include <NTSecAPI.h>

typedef WORD ATOM;
typedef int BOOL;
typedef BYTE BOOLEAN;
typedef unsigned char BYTE;
typedef char CCHAR;
typedef char CHAR;
typedef DWORD COLORREF;
typedef unsigned long DWORD;
typedef uint64_t DWORDLONG;
typedef ULONG_PTR DWORD_PTR;
typedef unsigned int DWORD32;
typedef uint64_t DWORD64;
typedef float FLOAT;
typedef HANDLE HACCEL;
typedef int HALF_PTR;
typedef short HALF_PTR;
typedef PVOID HANDLE;
typedef HANDLE HBITMAP;
typedef HANDLE HBRUSH;
typedef HANDLE HCOLORSPACE;
typedef HANDLE HCONV;
typedef HANDLE HCONVLIST;
typedef HICON HCURSOR;
typedef HANDLE HDC;
typedef HANDLE HDDEDATA;
typedef HANDLE HDESK;
typedef HANDLE HDROP;
typedef HANDLE HDWP;
typedef HANDLE HENHMETAFILE;
typedef int HFILE;
typedef HANDLE HFONT;
typedef HANDLE HGDIOBJ;
typedef HANDLE HGLOBAL;
typedef HANDLE HHOOK;
typedef HANDLE HICON;
typedef HANDLE HINSTANCE;
typedef HANDLE HKEY;
typedef HANDLE HKL;
typedef HANDLE HLOCAL;
typedef HANDLE HMENU;
typedef HANDLE HMETAFILE;
typedef HINSTANCE HMODULE;
typedef HANDLE HMONITOR;
typedef HANDLE HPALETTE;
typedef HANDLE HPEN;
typedef LONG HRESULT;
typedef HANDLE HRGN;
typedef HANDLE HRSRC;
typedef HANDLE HSZ;
typedef HANDLE WINSTA;
typedef HANDLE HWND;
typedef int INT;
typedef int64_t INT_PTR;
typedef int INT_PTR;
typedef signed char INT8;
typedef signed short INT16;
typedef signed int INT32;
typedef int64_t INT64;
typedef WORD LANGID;
typedef DWORD LCID;
typedef DWORD LCTYPE;
typedef DWORD LGRPID;
typedef long LONG;
typedef int64_t LONGLONG;
typedef double LONGLONG;
typedef int64_t LONG_PTR;
typedef long LONG_PTR;
typedef signed int LONG32;
typedef int64_t LONG64;
typedef LONG_PTR LPARAM;
typedef BOOL far *LPBOOL;
typedef BYTE far *LPBYTE;
typedef DWORD *LPCOLORREF;
typedef __nullterminated CONST CHAR *LPCSTR;
typedef LPCWSTR LPCTSTR;
typedef LPCSTR LPCTSTR;
typedef CONST void *LPCVOID;
typedef CONST WCHAR *LPCWSTR;
typedef DWORD *LPDWORD;
typedef HANDLE *LPHANDLE;
typedef int *LPINT;
typedef long *LPLONG;
typedef CHAR *LPSTR;
typedef LPWSTR LPTSTR;
typedef LPSTR LPTSTR;
typedef void *LPVOID;
typedef WORD *LPWORD;
typedef WCHAR *LPWSTR;
typedef LONG_PTR LRESULT;
typedef BOOL *PBOOL;
typedef BOOLEAN *PBOOLEAN;
typedef BYTE *PBYTE;
typedef CHAR *PCHAR;
typedef CONST CHAR *PCSTR;
typedef LPCWSTR PCTSTR;
typedef LPCSTR PCTSTR;
typedef CONST WCHAR *PCWSTR;
typedef DWORD *PDWORD;
typedef DWORDLONG *PDWORDLONG;
typedef DWORD_PTR *PDWORD_PTR;
typedef DWORD32 *PDWORD32;
typedef DWORD64 *PDWORD64;
typedef FLOAT *PFLOAT;
typedef HALF_PTR *PHALF_PTR;
typedef HALF_PTR *PHALF_PTR;
typedef HANDLE *PHANDLE;
typedef HKEY *PHKEY;
typedef int *PINT;
typedef INT_PTR *PINT_PTR;
typedef INT8 *PINT8;
typedef INT16 *PINT16;
typedef INT32 *PINT32;
typedef INT64 *PINT64;
typedef PDWORD PLCID;
typedef LONG *PLONG;
typedef LONGLONG *PLONGLONG;
typedef LONG_PTR *PLONG_PTR;
typedef LONG32 *PLONG32;
typedef LONG64 *PLONG64;
typedef SHORT *PSHORT;
typedef SIZE_T *PSIZE_T;
typedef SSIZE_T *PSSIZE_T;
typedef CHAR *PSTR;
typedef TBYTE *PTBYTE;
typedef TCHAR *PTCHAR;
typedef LPWSTR PTSTR;
typedef LPSTR PTSTR;
typedef UCHAR *PUCHAR;
typedef UHALF_PTR *PUHALF_PTR;
typedef UHALF_PTR *PUHALF_PTR;
typedef UINT *PUINT;
typedef UINT_PTR *PUINT_PTR;
typedef UINT8 *PUINT8;
typedef UINT16 *PUINT16;
typedef UINT32 *PUINT32;
typedef UINT64 *PUINT64;
typedef ULONG *PULONG;
typedef ULONGLONG *PULONGLONG;
typedef ULONG_PTR *PULONG_PTR;
typedef ULONG32 *PULONG32;
typedef ULONG64 *PULONG64;
typedef USHORT *PUSHORT;
typedef void *PVOID;
typedef WCHAR *PWCHAR;
typedef WORD *PWORD;
typedef WCHAR *PWSTR;
typedef uint64_t QWORD;
typedef HANDLE SC_HANDLE;
typedef LPVOID SC_LOCK;
typedef HANDLE SERVICE_STATUS_HANDLE;
typedef short SHORT;
typedef ULONG_PTR SIZE_T;
typedef LONG_PTR SSIZE_T;
typedef WCHAR TBYTE;
typedef unsigned char TBYTE;
typedef WCHAR TCHAR;
typedef char TCHAR;
typedef unsigned char UCHAR;
typedef unsigned int UHALF_PTR;
typedef unsigned short UHALF_PTR;
typedef unsigned int UINT;
typedef uint64_t UINT_PTR;
typedef unsigned int UINT_PTR;
typedef unsigned char UINT8;
typedef unsigned short UINT16;
typedef unsigned int UINT32;
typedef uint64_t UINT64;
typedef unsigned long ULONG;
typedef uint64_t ULONGLONG;
typedef double ULONGLONG;
typedef uint64_t ULONG_PTR;
typedef unsigned long ULONG_PTR;
typedef unsigned int ULONG32;
typedef uint64_t ULONG64;
typedef UNICODE_STRING *PUNICODE_STRING;
typedef const UNICODE_STRING *PCUNICODE_STRING;
typedef unsigned short USHORT;
typedef LONGLONG USN;
typedef wchar_t WCHAR;
typedef unsigned short WORD;
typedef UINT_PTR WPARAM;
